import { useEffect,useMemo,useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { Card,CardContent,CardHeader,CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { RefreshCw,ShieldCheck } from 'lucide-react';

type AuditRow={id:string;event_type:string;actor_role:string|null;source_device:string;entity_type:string;entity_id:string|null;details:Record<string,unknown>;created_at:string};
export default function AuditLog(){const [rows,setRows]=useState<AuditRow[]>([]),[search,setSearch]=useState(''),[loading,setLoading]=useState(false);const load=async()=>{setLoading(true);const {data,error}=await (supabase.from('audit_logs' as any) as any).select('id,event_type,actor_role,source_device,entity_type,entity_id,details,created_at').order('created_at',{ascending:false}).limit(500);setLoading(false);if(!error)setRows((data||[]) as AuditRow[]);};useEffect(()=>{void load();},[]);const filtered=useMemo(()=>{const q=search.toLowerCase().trim();return q?rows.filter(r=>[r.event_type,r.actor_role,r.source_device,r.entity_type,r.entity_id,JSON.stringify(r.details)].some(v=>String(v||'').toLowerCase().includes(q))):rows;},[rows,search]);return <div className="space-y-4"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold flex items-center gap-2"><ShieldCheck/>Audit Log</h1><p className="text-muted-foreground">Immutable history of sensitive POS actions.</p></div><Button variant="outline" onClick={()=>void load()} disabled={loading}><RefreshCw className="mr-2 h-4 w-4"/>{loading?'Loading...':'Refresh'}</Button></div><Input placeholder="Search action, role, entity or details..." value={search} onChange={e=>setSearch(e.target.value)}/><Card><CardHeader><CardTitle>Activity ({filtered.length})</CardTitle></CardHeader><CardContent className="space-y-2">{filtered.map(r=><div key={r.id} className="rounded-md border p-3"><div className="flex flex-wrap items-center gap-2"><b>{r.event_type.split('_').join(' ')}</b><Badge variant="outline">{r.entity_type}</Badge><Badge variant="secondary">{r.actor_role||'system'}</Badge><span className="ml-auto text-xs text-muted-foreground">{new Date(r.created_at).toLocaleString()}</span></div><div className="mt-1 text-xs text-muted-foreground">{r.entity_id||'—'} · {r.source_device}</div>{Object.keys(r.details||{}).length>0&&<pre className="mt-2 overflow-auto whitespace-pre-wrap rounded bg-muted p-2 text-xs">{JSON.stringify(r.details,null,2)}</pre>}</div>)}{!loading&&!filtered.length&&<p className="py-8 text-center text-muted-foreground">No audit events found.</p>}</CardContent></Card></div>}
