import {useMemo,useState} from 'react';
import {useRestaurant} from '@/contexts/RestaurantContext';
import {Card,CardContent,CardHeader,CardTitle} from '@/components/ui/card';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {Download,Search} from 'lucide-react';
import {format} from 'date-fns';
import {exportToCSV} from '@/lib/csvExport';
export default function ItemWiseSales(){
 const {orders,menuItems,menuCategories,settings}=useRestaurant();const [from,setFrom]=useState(format(new Date(Date.now()-6*86400000),'yyyy-MM-dd')),[to,setTo]=useState(format(new Date(),'yyyy-MM-dd')),[search,setSearch]=useState('');
 const rows=useMemo(()=>{const start=new Date(from+'T00:00:00'),end=new Date(to+'T23:59:59'),m=new Map<string,any>();orders.filter(o=>o.status==='completed'&&o.paymentStatus==='paid'&&new Date(o.createdAt)>=start&&new Date(o.createdAt)<=end).forEach(o=>o.items.forEach(i=>{const qty=Number(i.finalQuantity??i.quantity??0);if(qty<=0)return;const mi=menuItems.find(x=>x.id===i.menuItemId),cat=menuCategories.find(c=>c.id===mi?.categoryId)?.name||'Other',key=i.menuItemId+'|'+(i.variantId||'');const r=m.get(key)||{item:i.menuItemName,variant:i.variantName||'',category:cat,quantity:0,gross:0,cost:0,orders:new Set<string>()};r.quantity+=qty;r.gross+=Number(i.unitPrice||0)*qty;r.cost+=Number(i.unitCostAtSale??mi?.recipeCost??0)*qty;r.orders.add(o.id);m.set(key,r)}));return [...m.values()].map(r=>({...r,orders:r.orders.size,profit:r.gross-r.cost})).filter(r=>[r.item,r.variant,r.category].join(' ').toLowerCase().includes(search.toLowerCase())).sort((a,b)=>b.gross-a.gross)},[orders,menuItems,menuCategories,from,to,search]);
 const totals=rows.reduce((a,r)=>({qty:a.qty+r.quantity,sales:a.sales+r.gross,cost:a.cost+r.cost,profit:a.profit+r.profit}),{qty:0,sales:0,cost:0,profit:0});
 const exp=()=>exportToCSV(rows,[{key:'item',header:'Item'},{key:'variant',header:'Variant'},{key:'category',header:'Category'},{key:'orders',header:'Orders'},{key:'quantity',header:'Quantity Sold'},{key:'gross',header:'Sales'},{key:'cost',header:'Cost Snapshot'},{key:'profit',header:'Gross Profit'}],`item-wise-sales-${from}-to-${to}`);
 return <div className="space-y-5"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold">Item Wise Sales</h1><p className="text-muted-foreground">Paid completed item sales using final billable quantities.</p></div><Button onClick={exp}><Download className="mr-2 h-4 w-4"/>Export CSV</Button></div><Card><CardContent className="grid gap-3 pt-6 md:grid-cols-3"><Input type="date" value={from} onChange={e=>setFrom(e.target.value)}/><Input type="date" value={to} onChange={e=>setTo(e.target.value)}/><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input className="pl-9" placeholder="Search item, variant, category" value={search} onChange={e=>setSearch(e.target.value)}/></div></CardContent></Card><div className="grid gap-3 md:grid-cols-4">{[['Quantity Sold',totals.qty],['Item Sales',totals.sales],['Cost',totals.cost],['Gross Profit',totals.profit]].map(([n,v],i)=><Card key={String(n)}><CardContent className="pt-5"><p className="text-sm text-muted-foreground">{n}</p><p className="text-xl font-bold">{i?settings.currencySymbol+' ':''}{Number(v).toLocaleString(undefined,{maximumFractionDigits:0})}</p></CardContent></Card>)}</div><Card><CardHeader><CardTitle>{rows.length} Items / Variants</CardTitle></CardHeader><CardContent className="overflow-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="py-2">Item</th><th>Variant</th><th>Category</th><th className="text-right">Orders</th><th className="text-right">Qty</th><th className="text-right">Sales</th><th className="text-right">Cost</th><th className="text-right">Gross Profit</th></tr></thead><tbody>{rows.map(r=><tr key={r.item+'|'+r.variant} className="border-b"><td className="py-2 font-medium">{r.item}</td><td>{r.variant||'—'}</td><td>{r.category}</td><td className="text-right">{r.orders}</td><td className="text-right">{r.quantity}</td><td className="text-right">{settings.currencySymbol} {r.gross.toLocaleString()}</td><td className="text-right">{settings.currencySymbol} {r.cost.toLocaleString()}</td><td className="text-right font-semibold">{settings.currencySymbol} {r.profit.toLocaleString()}</td></tr>)}</tbody></table>{!rows.length&&<p className="py-8 text-center text-muted-foreground">No item sales found.</p>}</CardContent></Card></div>
}