import { useMemo,useState } from 'react';
import { useRestaurant } from '@/contexts/RestaurantContext';
import { Card,CardContent,CardHeader,CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { Download,BarChart3 } from 'lucide-react';
import { exportToCSV } from '@/lib/csvExport';
import { format } from 'date-fns';

export default function Reports(){
 const {orders,settings}=useRestaurant();
 const [from,setFrom]=useState(format(new Date(Date.now()-6*86400000),'yyyy-MM-dd')),[to,setTo]=useState(format(new Date(),'yyyy-MM-dd')),[type,setType]=useState('all'),[payment,setPayment]=useState('all');
 const completed=useMemo(()=>orders.filter(o=>{if(o.status!=='completed'||o.paymentStatus!=='paid')return false;const d=new Date(o.createdAt),start=new Date(from+'T00:00:00'),end=new Date(to+'T23:59:59');return d>=start&&d<=end&&(type==='all'||o.orderType===type)&&(payment==='all'||o.paymentMethod===payment)}),[orders,from,to,type,payment]);
 const revenue=completed.reduce((s,o)=>s+Number(o.total||0),0),subtotal=completed.reduce((s,o)=>s+Number(o.subtotal||0),0),discount=completed.reduce((s,o)=>s+Number(o.discount||0),0),tax=completed.reduce((s,o)=>s+Number(o.tax||0),0),avg=completed.length?revenue/completed.length:0;
 const group=(key:(o:any)=>string)=>Object.values(completed.reduce((a:any,o:any)=>{const k=key(o)||'Unknown';a[k]??={name:k,orders:0,sales:0};a[k].orders++;a[k].sales+=Number(o.total||0);return a},{})).sort((a:any,b:any)=>b.sales-a.sales) as any[];
 const paymentRows=group(o=>o.paymentMethod||'unpaid'),typeRows=group(o=>o.fulfillmentType||o.orderType),hourRows=group(o=>String(new Date(o.createdAt).getHours()).padStart(2,'0')+':00'),waiterRows=group(o=>o.waiterName||'No waiter');
 const exportSummary=()=>exportToCSV(completed.map(o=>({order:o.orderNumber,date:new Date(o.createdAt).toLocaleString(),type:o.fulfillmentType||o.orderType,payment:o.paymentMethod,subtotal:o.subtotal,discount:o.discount,tax:o.tax,total:o.total,waiter:o.waiterName||''})),[{key:'order',header:'Order'},{key:'date',header:'Date'},{key:'type',header:'Order Type'},{key:'payment',header:'Payment Mode'},{key:'subtotal',header:'Subtotal'},{key:'discount',header:'Discount'},{key:'tax',header:'Tax'},{key:'total',header:'Net Sale'},{key:'waiter',header:'Waiter'}],`sales-summary-${from}-to-${to}`);
 const Table=({title,rows}:{title:string;rows:any[]})=><Card><CardHeader><CardTitle className="text-base">{title}</CardTitle></CardHeader><CardContent><div className="space-y-2">{rows.map(r=><div key={r.name} className="grid grid-cols-[1fr_auto_auto] gap-4 border-b py-2 text-sm"><span className="capitalize">{r.name}</span><span>{r.orders} orders</span><b>{settings.currencySymbol} {r.sales.toLocaleString()}</b></div>)}{!rows.length&&<p className="text-sm text-muted-foreground">No data for selected filters.</p>}</div></CardContent></Card>;
 return <div className="space-y-6"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold flex items-center gap-2"><BarChart3/>Sales Reporting Center</h1><p className="text-muted-foreground">Paid completed sales with date, order type and payment filters.</p></div><Button onClick={exportSummary}><Download className="mr-2 h-4 w-4"/>Export Sales CSV</Button></div>
 <Card><CardContent className="grid gap-3 pt-6 md:grid-cols-4"><Input type="date" value={from} onChange={e=>setFrom(e.target.value)}/><Input type="date" value={to} onChange={e=>setTo(e.target.value)}/><Select value={type} onValueChange={setType}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All Order Types</SelectItem><SelectItem value="dine-in">Dine-In</SelectItem><SelectItem value="takeaway">Takeaway</SelectItem><SelectItem value="delivery">Delivery</SelectItem><SelectItem value="online">Online</SelectItem></SelectContent></Select><Select value={payment} onValueChange={setPayment}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All Payments</SelectItem><SelectItem value="cash">Cash</SelectItem><SelectItem value="card">Card</SelectItem><SelectItem value="mobile">Mobile</SelectItem></SelectContent></Select></CardContent></Card>
 <div className="grid gap-3 md:grid-cols-5">{[['Net Sales',revenue],['Gross / Subtotal',subtotal],['Discounts',discount],['Tax',tax],['Avg Order',avg]].map(([n,v])=><Card key={String(n)}><CardContent className="pt-5"><p className="text-sm text-muted-foreground">{n}</p><p className="text-xl font-bold">{settings.currencySymbol} {Number(v).toLocaleString(undefined,{maximumFractionDigits:0})}</p></CardContent></Card>)}</div>
 <div className="grid gap-4 md:grid-cols-2"><Table title="Payment Mode Wise" rows={paymentRows}/><Table title="Order Type Wise" rows={typeRows}/><Table title="Hourly Sales" rows={hourRows}/><Table title="Waiter Wise Sales" rows={waiterRows}/></div>
 <Card><CardHeader><CardTitle>Sales Summary · {completed.length} orders</CardTitle></CardHeader><CardContent className="overflow-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="py-2">Order</th><th>Date</th><th>Type</th><th>Payment</th><th>Waiter</th><th className="text-right">Discount</th><th className="text-right">Net Sale</th></tr></thead><tbody>{completed.slice().sort((a,b)=>+new Date(b.createdAt)-+new Date(a.createdAt)).map(o=><tr key={o.id} className="border-b"><td className="py-2 font-medium">{o.orderNumber}</td><td>{new Date(o.createdAt).toLocaleString()}</td><td className="capitalize">{o.fulfillmentType||o.orderType}</td><td className="capitalize">{o.paymentMethod}</td><td>{o.waiterName||'—'}</td><td className="text-right">{settings.currencySymbol} {Number(o.discount||0).toLocaleString()}</td><td className="text-right font-semibold">{settings.currencySymbol} {Number(o.total||0).toLocaleString()}</td></tr>)}</tbody></table></CardContent></Card></div>
}