-- Task 14: harden payment collection and settlement.
create or replace function public.record_order_payment(p_order_id uuid,p_amount numeric,p_payment_method text,p_reference text default null,p_idempotency_key text default null,p_source_device text default 'POS')
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_user uuid:=auth.uid();v_order public.orders%rowtype;v_paid numeric:=0;v_payment_id uuid;v_status text;v_existing public.order_payments%rowtype;
begin
 if v_user is null or not public.has_permission(v_user,'payment.collect') then raise exception 'Payment collection not permitted';end if;if p_payment_method not in ('cash','card','mobile') then raise exception 'Invalid payment method';end if;if p_amount<=0 then raise exception 'Payment amount must be positive';end if;
 select * into v_order from public.orders where id=p_order_id for update;if not found then raise exception 'Order not found';end if;if v_order.status in ('cancelled','refunded') or v_order.operational_status in ('cancelled','refunded') or v_order.payment_status='refunded' then raise exception 'Cancelled/refunded order cannot receive payment';end if;
 if p_idempotency_key is not null then select * into v_existing from public.order_payments where idempotency_key=p_idempotency_key limit 1;if found then if v_existing.order_id<>p_order_id then raise exception 'Payment key belongs to another order';end if;return jsonb_build_object('payment_id',v_existing.id,'duplicate',true,'payment_status',v_order.payment_status);end if;end if;
 select coalesce(sum(amount),0) into v_paid from public.order_payments where order_id=p_order_id and status='paid';if v_paid+p_amount>v_order.total then raise exception 'Payment exceeds outstanding balance';end if;
 insert into public.order_payments(order_id,amount,payment_method,reference,collected_by,idempotency_key) values(p_order_id,p_amount,p_payment_method,nullif(trim(p_reference),''),v_user,p_idempotency_key) returning id into v_payment_id;
 v_paid:=v_paid+p_amount;v_status:=case when v_paid>=v_order.total then 'paid' when v_paid>0 then 'partially_paid' else 'unpaid' end;update public.orders set payment_status=v_status,payment_method=p_payment_method,updated_at=now() where id=p_order_id;
 insert into public.order_activity_log(order_id,event_type,actor_user_id,actor_role,source_device,entity_type,entity_id,details) values(p_order_id,'PAYMENT_RECEIVED',v_user,public.get_user_role(v_user)::text,p_source_device,'payment',v_payment_id,jsonb_build_object('amount',p_amount,'payment_method',p_payment_method,'reference',nullif(trim(p_reference),''),'total_paid',v_paid,'outstanding',greatest(v_order.total-v_paid,0),'payment_status',v_status));
 return jsonb_build_object('payment_id',v_payment_id,'duplicate',false,'total_paid',v_paid,'outstanding',greatest(v_order.total-v_paid,0),'payment_status',v_status);
end $$;
create or replace function public.settle_order_atomic(p_order_id uuid,p_payment_method text,p_idempotency_key text default null,p_source_device text default 'POS')
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_user uuid:=auth.uid();v_order public.orders%rowtype;v_paid numeric:=0;v_due numeric:=0;v_payment_id uuid;v_existing public.order_payments%rowtype;
begin
 if v_user is null or not public.has_permission(v_user,'payment.collect') then raise exception 'Payment collection not permitted';end if;if p_payment_method not in ('cash','card','mobile') then raise exception 'Invalid payment method';end if;select * into v_order from public.orders where id=p_order_id for update;if not found then raise exception 'Order not found';end if;
 if v_order.status in ('cancelled','refunded') or v_order.operational_status in ('cancelled','refunded') or v_order.payment_status='refunded' then raise exception 'Cancelled/refunded order cannot be settled';end if;
 if v_order.payment_status='paid' and (v_order.status='completed' or v_order.operational_status='completed') then update public.restaurant_tables set status='available',current_order_id=null where current_order_id=p_order_id;return jsonb_build_object('order_id',p_order_id,'payment_status','paid','operational_status','completed','amount_collected',0,'duplicate',true);end if;
 if p_idempotency_key is not null then select * into v_existing from public.order_payments where idempotency_key=p_idempotency_key limit 1;if found then if v_existing.order_id<>p_order_id then raise exception 'Payment key belongs to another order';end if;if v_order.payment_status='paid' then update public.orders set operational_status='completed',status='completed',completed_at=coalesce(completed_at,now()),updated_at=now() where id=p_order_id;update public.restaurant_tables set status='available',current_order_id=null where current_order_id=p_order_id;end if;return jsonb_build_object('order_id',p_order_id,'payment_status',v_order.payment_status,'operational_status',case when v_order.payment_status='paid' then 'completed' else v_order.operational_status end,'amount_collected',0,'duplicate',true);end if;end if;
 select coalesce(sum(amount),0) into v_paid from public.order_payments where order_id=p_order_id and status='paid';v_due:=greatest(coalesce(v_order.total,0)-v_paid,0);if v_due>0 then insert into public.order_payments(order_id,amount,payment_method,collected_by,idempotency_key) values(p_order_id,v_due,p_payment_method,v_user,p_idempotency_key) returning id into v_payment_id;end if;
 update public.orders set payment_status='paid',payment_method=p_payment_method,operational_status='completed',status='completed',completed_at=coalesce(completed_at,now()),updated_at=now() where id=p_order_id;update public.restaurant_tables set status='available',current_order_id=null where current_order_id=p_order_id;
 insert into public.order_activity_log(order_id,event_type,actor_user_id,actor_role,source_device,entity_type,entity_id,details) values(p_order_id,'ORDER_SETTLED',v_user,public.get_user_role(v_user)::text,p_source_device,'order',p_order_id,jsonb_build_object('previously_paid',v_paid,'amount_collected',v_due,'total_paid',v_paid+v_due,'payment_method',p_payment_method,'payment_status','paid','operational_status','completed'));
 return jsonb_build_object('order_id',p_order_id,'payment_status','paid','operational_status','completed','amount_collected',v_due,'total_paid',v_paid+v_due,'duplicate',false);
end $$;
create or replace function public.get_order_payment_summary(p_order_id uuid) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_user uuid:=auth.uid();v_total numeric;v_paid numeric;begin if v_user is null or (not public.has_permission(v_user,'payment.collect') and not public.has_permission(v_user,'order.view_all')) then raise exception 'Not authorized';end if;select total into v_total from public.orders where id=p_order_id;if not found then raise exception 'Order not found';end if;select coalesce(sum(amount),0) into v_paid from public.order_payments where order_id=p_order_id and status='paid';return jsonb_build_object('order_id',p_order_id,'total',v_total,'paid',v_paid,'outstanding',greatest(v_total-v_paid,0));end $$;
revoke all on function public.get_order_payment_summary(uuid) from public,anon;grant execute on function public.get_order_payment_summary(uuid) to authenticated;