-- Task 13: delivery details and rider assignment foundation.
create table if not exists public.riders (id uuid primary key default gen_random_uuid(),name text not null,phone text,is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.riders enable row level security;
create policy "authenticated can view riders" on public.riders for select to authenticated using (true);
create policy "management can manage riders" on public.riders for all to authenticated using (public.has_role(auth.uid(),'admin') or public.has_role(auth.uid(),'manager')) with check (public.has_role(auth.uid(),'admin') or public.has_role(auth.uid(),'manager'));
alter table public.orders add column if not exists customer_phone text;
alter table public.orders add column if not exists delivery_address text;
alter table public.orders add column if not exists rider_id uuid references public.riders(id);
alter table public.orders add column if not exists rider_name text;
alter table public.orders add column if not exists dispatched_at timestamptz;
create or replace function public.save_delivery_details(p_order_id uuid,p_customer_name text,p_customer_phone text,p_delivery_address text) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_user uuid:=auth.uid();v_order public.orders%rowtype;v_customer_id uuid;v_name text:=btrim(p_customer_name);v_phone text:=btrim(p_customer_phone);v_address text:=btrim(p_delivery_address);
begin if v_user is null or (not public.has_permission(v_user,'order.edit') and not public.has_permission(v_user,'payment.collect')) then raise exception 'Not authorized';end if;if v_name='' or v_phone='' or v_address='' then raise exception 'Customer name, phone and delivery address are required';end if;select * into v_order from public.orders where id=p_order_id for update;if not found then raise exception 'Order not found';end if;if coalesce(v_order.fulfillment_type,v_order.order_type)<>'delivery' and v_order.order_type<>'online' then raise exception 'Not a delivery order';end if;select id into v_customer_id from public.customers where phone=v_phone order by updated_at desc limit 1;if v_customer_id is null then insert into public.customers(name,phone,address) values(v_name,v_phone,v_address) returning id into v_customer_id;else update public.customers set name=v_name,address=v_address,updated_at=now() where id=v_customer_id;end if;update public.orders set customer_id=v_customer_id,customer_name=v_name,customer_phone=v_phone,delivery_address=v_address,updated_at=now() where id=p_order_id;return jsonb_build_object('order_id',p_order_id,'customer_id',v_customer_id,'customer_name',v_name,'customer_phone',v_phone,'delivery_address',v_address);end $$;
revoke all on function public.save_delivery_details(uuid,text,text,text) from public,anon;grant execute on function public.save_delivery_details(uuid,text,text,text) to authenticated;
create or replace function public.assign_order_rider(p_order_id uuid,p_rider_id uuid) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_user uuid:=auth.uid();v_order public.orders%rowtype;v_rider public.riders%rowtype;
begin if v_user is null or not public.has_permission(v_user,'order.edit') then raise exception 'Rider assignment not permitted';end if;select * into v_order from public.orders where id=p_order_id for update;if not found then raise exception 'Order not found';end if;if coalesce(v_order.fulfillment_type,v_order.order_type)<>'delivery' and v_order.order_type<>'online' then raise exception 'Not a delivery order';end if;if v_order.status in ('completed','cancelled','refunded') then raise exception 'Closed order cannot be assigned';end if;select * into v_rider from public.riders where id=p_rider_id and is_active=true;if not found then raise exception 'Select an active rider';end if;update public.orders set rider_id=v_rider.id,rider_name=v_rider.name,updated_at=now() where id=p_order_id;insert into public.order_activity_log(order_id,event_type,actor_user_id,actor_role,source_device,entity_type,entity_id,before_data,after_data) values(p_order_id,'RIDER_ASSIGNED',v_user,public.get_user_role(v_user)::text,'POS','order',p_order_id,jsonb_build_object('rider_id',v_order.rider_id,'rider_name',v_order.rider_name),jsonb_build_object('rider_id',v_rider.id,'rider_name',v_rider.name));return jsonb_build_object('order_id',p_order_id,'rider_id',v_rider.id,'rider_name',v_rider.name);end $$;
revoke all on function public.assign_order_rider(uuid,uuid) from public,anon;grant execute on function public.assign_order_rider(uuid,uuid) to authenticated;